# Generated by Django 4.1.5 on 2023-01-29 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_polishes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polishes',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polishes', to='main_app.brands'),
        ),
    ]
