# Generated by Django 4.1.5 on 2023-01-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_polishes_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Polishes',
            new_name='Polish',
        ),
    ]
